"""Pure-Python Hawkes and point-process tools."""

from .base import Base, BaseEstimator, History, ThreadPool, TimeFunction, actual_kwargs
from .base_model import (
    Model,
    ModelFirstOrder,
    ModelGeneralizedLinear,
    ModelLabelsFeatures,
    ModelLipschitz,
    ModelSecondOrder,
    ModelSelfConcordant,
)
from .linear_model import (
    LearnerLinReg,
    LearnerLogReg,
    LearnerPoisReg,
    LinearRegression,
    LogisticRegression,
    ModelHinge,
    ModelLinReg,
    ModelLogReg,
    ModelPoisReg,
    ModelQuadraticHinge,
    ModelSmoothedHinge,
    PoissonRegression,
    SimuLinReg,
    SimuLogReg,
    SimuPoisReg,
    weights_sparse_gauss,
)
from .metrics import support_fdp, support_recall
from .plot import (
    plot_basis_kernels,
    plot_estimated_intensity,
    plot_hawkes_baseline_and_kernels,
    plot_hawkes_kernel_norms,
    plot_hawkes_kernels,
    plot_history,
    plot_point_process,
    plot_timefunction,
    qq_plots,
    stems,
)
from .preprocessing import (
    FeaturesBinarizer,
    LongitudinalFeaturesLagger,
    LongitudinalFeaturesProduct,
    LongitudinalSamplesFilter,
    check_censoring_consistency,
    check_longitudinal_features_consistency,
    safe_array,
)
from .robust import (
    ModelAbsoluteRegression,
    ModelEpsilonInsensitive,
    ModelHuber,
    ModelLinRegWithIntercepts,
    ModelModifiedHuber,
    RobustLinearRegression,
    std_iqr,
    std_mad,
)
from .simulation import features_normal_cov_toeplitz, features_normal_cov_uniform, weights_sparse_exp
from .survival import (
    ConvSCCS,
    CoxRegression,
    CustomEffects,
    ModelCoxRegPartialLik,
    ModelSCCS,
    SimuCoxReg,
    SimuCoxRegWithCutPoints,
    SimuSCCS,
    kaplan_meier,
    nelson_aalen,
)

__all__ = [
    "BaseEstimator",
    "Base",
    "History",
    "ThreadPool",
    "TimeFunction",
    "actual_kwargs",
    "Model",
    "ModelFirstOrder",
    "ModelSecondOrder",
    "ModelLabelsFeatures",
    "ModelSelfConcordant",
    "ModelGeneralizedLinear",
    "ModelLipschitz",
    "ModelLinReg",
    "ModelLogReg",
    "ModelPoisReg",
    "ModelHinge",
    "ModelQuadraticHinge",
    "ModelSmoothedHinge",
    "LinearRegression",
    "LogisticRegression",
    "PoissonRegression",
    "LearnerLinReg",
    "LearnerLogReg",
    "LearnerPoisReg",
    "SimuLinReg",
    "SimuLogReg",
    "SimuPoisReg",
    "weights_sparse_gauss",
    "weights_sparse_exp",
    "features_normal_cov_uniform",
    "support_fdp",
    "support_recall",
    "FeaturesBinarizer",
    "LongitudinalFeaturesProduct",
    "LongitudinalFeaturesLagger",
    "LongitudinalSamplesFilter",
    "safe_array",
    "check_censoring_consistency",
    "check_longitudinal_features_consistency",
    "ModelAbsoluteRegression",
    "ModelEpsilonInsensitive",
    "ModelHuber",
    "ModelLinRegWithIntercepts",
    "ModelModifiedHuber",
    "RobustLinearRegression",
    "features_normal_cov_toeplitz",
    "std_iqr",
    "std_mad",
    "SimuCoxReg",
    "CoxRegression",
    "ModelCoxRegPartialLik",
    "ModelSCCS",
    "SimuCoxRegWithCutPoints",
    "SimuSCCS",
    "CustomEffects",
    "ConvSCCS",
    "kaplan_meier",
    "nelson_aalen",
    "plot_point_process",
    "plot_hawkes_kernels",
    "plot_hawkes_kernel_norms",
    "plot_hawkes_baseline_and_kernels",
    "plot_basis_kernels",
    "plot_estimated_intensity",
    "plot_history",
    "plot_timefunction",
    "qq_plots",
    "stems",
]

__version__ = "0.1.0"
